# Basic
title: icurious
subtitle: 行万里路，读万卷书.
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">欢迎到我的小站来做客！</a>
description: Hi,你好,我是icurious,一名小小的见习魔法师,目前还在魔法学校学习,致力于基础魔法的研究和应用,努力成为一名优秀的魔法师。
creator: <a href="http://www.blankspace.cn">@icurious</a>

url: "http://www.blankspace.cn"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客
# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: CSDN,       in_site: false,  description: icurious's CSDN blog,    url: 'http://blog.csdn.net/icurious'}
    - {title: GitHub,     in_site: false,  description: icurious's GitHub,    url: 'https://github.com/icurious'}
    - {title: 关于,        in_site: true,  description: 关于作者 icurious,       url: '/info/about'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: icurious
    # duoshuo: 
    
# Social
social:
    weibo: icurious
    github: icurious
    twitter: icurious
    gplus: 112373242775367333102
    rss: /feed.xml
    mail: nihaoworld@outlook.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-86995833-1
    host: www.blankspace.cn
